AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: A function that processes data from a Kinesis stream.
Resources:
  KinesisMessageHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: main.handler
      Runtime: nodejs16.x
      Architectures:
        - arm64
      Timeout: 30
      MemorySize: 512
      Tracing: Active
      Events:
        Stream:
          Type: Kinesis
          Properties:
            Stream: !GetAtt streamConsumer.ConsumerARN
            StartingPosition: LATEST
            BatchSize: 1
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        External:
          - "pg-native"
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - main.ts
  streamConsumer:
    Type: "AWS::Kinesis::StreamConsumer"
    Properties:
      StreamARN: arn:aws:kinesis:us-east-1:123456789123:stream/monitoring-data-stream
      ConsumerName: "MonitoringKDSConsumer"
